#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 14 17:57:07 YEKT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=14
shaderPack=Body-Camera-Shader-V1.2.1.zip
enableShaders=false
